FROM node:20-alpine

WORKDIR /app

COPY . .

RUN npm install

RUN ./node_modules/.bin/prisma generate --schema=packages/db/prisma/schema.prisma

WORKDIR /app/apps/user-app
RUN npm run build

EXPOSE 3000

CMD ["npm","run","start"]
